packages:
  - bench
  - bindings/*
  - examples/*
  - packages/*
  - test/bundlers
  - test/cli
  - test/fixtures/*

autoInstallPeers: false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - lmdb
  - msgpackr-extract
